// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9mwpaaznaI-SSjydo5TRTp8LrEENqJ1Y',
    appId: '1:125191806247:web:a32fa4d2ca1efd9ac69d02',
    messagingSenderId: '125191806247',
    projectId: 'voice-chat-b428d',
    authDomain: 'voice-chat-b428d.firebaseapp.com',
    storageBucket: 'voice-chat-b428d.appspot.com',
    measurementId: 'G-GK02XEQBSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6TyToq2tFgs1bHXVEyQ4tatFcVlvBzV8',
    appId: '1:125191806247:android:c120071daa18dcf9c69d02',
    messagingSenderId: '125191806247',
    projectId: 'voice-chat-b428d',
    storageBucket: 'voice-chat-b428d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbV-rU_LsmE9FK0IsNZzdW0wYPR-spsE',
    appId: '1:125191806247:ios:9151fdef2d47210cc69d02',
    messagingSenderId: '125191806247',
    projectId: 'voice-chat-b428d',
    storageBucket: 'voice-chat-b428d.appspot.com',
    iosBundleId: 'com.msar.voiceChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbV-rU_LsmE9FK0IsNZzdW0wYPR-spsE',
    appId: '1:125191806247:ios:9151fdef2d47210cc69d02',
    messagingSenderId: '125191806247',
    projectId: 'voice-chat-b428d',
    storageBucket: 'voice-chat-b428d.appspot.com',
    iosBundleId: 'com.msar.voiceChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9mwpaaznaI-SSjydo5TRTp8LrEENqJ1Y',
    appId: '1:125191806247:web:edeba548a93ca8fcc69d02',
    messagingSenderId: '125191806247',
    projectId: 'voice-chat-b428d',
    authDomain: 'voice-chat-b428d.firebaseapp.com',
    storageBucket: 'voice-chat-b428d.appspot.com',
    measurementId: 'G-9RQ6RF93F8',
  );
}
